services:
  weather_station_regiona:
    build: .
    container_name: weather_station_regionA
    environment:
      REGION: "regionA"
      AREAS: "areaA1"
      NATS_URL: "nats://100.26.146.73:4222"
    depends_on:
      - nats
    restart: unless-stopped

  weather_station_regionb:
    build: .
    container_name: weather_station_regionB
    environment:
      REGION: "regionB"
      AREAS: "areaB1"
      NATS_URL: "nats://100.26.146.73:4222"
    depends_on:
      - nats
    restart: unless-stopped