services:
  weather_station_regiona:
    build: .
    container_name: weather_station_regionA
    environment:
      REGION: "regionA"
      AREAS: "areaA1,areaA2"
      NATS_URL: "nats://nats:4222"
    restart: unless-stopped

  weather_station_regionb:
    build: .
    container_name: weather_station_regionB
    environment:
      REGION: "regionB"
      AREAS: "areaB1,areaB2,areaB3"
      NATS_URL: "nats://nats:4222"
    restart: unless-stopped
