services:
  weather_station_regiona:
    build: .
    container_name: weather_station_regionA
    environment:
      REGION: "regionA"
      AREAS: "areaA1"
      NATS_URL: "nats://98.95.255.36:4222"

  weather_station_regionb:
    build: .
    container_name: weather_station_regionB
    environment:
      REGION: "regionB"
      AREAS: "areaB1"
      NATS_URL: "nats://98.95.255.36:4222"