# this creates the following services as examples:

## NATS server
## One camera sender for areaA1 (in regionA -> EDGE CONNECTION)
## One camera sender for areaB1 (in regionB -> EDGE CONNECTION)
## One alarm radio for areaA1
## One alarm radio for areaB1

services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"

  camera_areaa1:
    build: ./camera
    environment:
      CAMERA_AREA: "areaA1"
      FRAMES_DIR: "/app/frames_cam01"
      FPS: 1
    depends_on:
      - nats

  camera_areab1:
    build: ./camera
    environment:
      CAMERA_AREA: "areaB1"
      FRAMES_DIR: "/app/frames_cam02"
      FPS: 1
    depends_on:
      - nats

  alarm_areaa1:
    build: ./alarm
    environment:
      ALARM_AREA: "areaA1"
    depends_on:
      - nats

  alarm_areab1:
    build: ./alarm
    environment:
      ALARM_AREA: "areaB1"
    depends_on:
      - nats
